"""Render a human-readable preview of the scraped CSVs into PREVIEW.md."""
import csv
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

OUT = Path("out")
PREVIEW = Path("PREVIEW.md")


def load(name):
    with (OUT / name).open(encoding="utf-8") as f:
        return list(csv.DictReader(f))


def fmt_block(text, max_chars=600):
    if not text:
        return "_(empty)_"
    t = text.strip()
    if len(t) > max_chars:
        t = t[:max_chars].rstrip() + " ..."
    indented = "\n".join("    " + line for line in t.splitlines())
    return indented


def render_paper(row, label):
    out = [f"## {label}", ""]
    for k in ["link", "title", "type", "submission_number", "primary_area", "keywords"]:
        out.append(f"- **{k}**: {row.get(k, '')}")
    out.append("")
    out.append("**Authors**")
    out.append("")
    for a in row.get("authors", "").split(";"):
        if a.strip():
            out.append(f"- {a.strip()}")
    out.append("")
    out.append("**Abstract**")
    out.append("")
    out.append(fmt_block(row.get("abstract", ""), 800))
    out.append("")
    out.append(f"**Meta Reviewer:** {row.get('Meta Reviewer','')}")
    out.append("")
    out.append("**Meta Review**")
    out.append("")
    out.append(fmt_block(row.get("Meta Review", ""), 1000))
    out.append("")
    # find all review columns
    review_idxs = []
    for k in row:
        if k.startswith("Review ") and k.split()[-1].isdigit() and k.count(" ") == 1:
            n = int(k.split()[-1])
            if row[k]:
                review_idxs.append(n)
    for n in sorted(set(review_idxs)):
        reviewer = row.get(f"Reviewer {n}", "")
        out.append(f"### Review {n} — {reviewer}")
        ratings = []
        for k, v in row.items():
            prefix = f"Review {n} "
            if k.startswith(prefix) and k != f"Review {n}" and k != f"Rebuttal {n}":
                if v != "":
                    ratings.append(f"{k.replace(prefix, '')}={v}")
        if ratings:
            out.append("")
            out.append("Ratings: " + ", ".join(ratings))
        out.append("")
        out.append(fmt_block(row.get(f"Review {n}", ""), 700))
        out.append("")
        rebuttal = row.get(f"Rebuttal {n}", "")
        out.append(f"**Rebuttal {n} (author response, reviewer quotes stripped):**")
        out.append("")
        out.append(fmt_block(rebuttal, 700))
        out.append("")
    gen = row.get("General Response", "")
    if gen:
        out.append("### General Response (to all reviewers)")
        out.append("")
        out.append(fmt_block(gen, 700))
        out.append("")
    return "\n".join(out)


def render_author(row, label):
    out = [f"## {label}", ""]
    for k in ["Link", "Name", "Personal Links", "Expertise"]:
        out.append(f"- **{k}**: {row.get(k, '')}")
    out.append("")
    out.append("**History**")
    out.append("")
    out.append("| # | Title | Location | Start | End |")
    out.append("|---|---|---|---|---|")
    i = 1
    while True:
        title = row.get(f"History {i} Title")
        if title is None:
            break
        if not title:
            i += 1
            if i > 12:
                break
            continue
        out.append(
            f"| {i} | {title} | {row[f'History {i} Location']} "
            f"| {row[f'History {i} Start']} | {row[f'History {i} End']} |"
        )
        i += 1
        if i > 30:
            break
    out.append("")
    return "\n".join(out)


def main():
    iclr_papers = load("ICLR_2026_Conference_papers.csv")
    iclr_authors = load("ICLR_2026_Conference_authors.csv")
    icml_papers = load("ICML_2025_Conference_papers.csv")

    sections = []
    sections.append(
        "# Scraper Output Preview\n\n"
        "Human-readable snapshot of `out/*.csv`. Generated by `preview.py`. "
        "Showing one paper per acceptance type from ICLR 2026 plus one ICML 2025 "
        "paper (to demonstrate cross-venue adaptivity) and a sample author profile."
    )

    sections.append(f"**Files generated:**\n\n"
                    f"- `out/ICLR_2026_Conference_papers.csv` — {len(iclr_papers)} rows, "
                    f"{len(iclr_papers[0])} cols\n"
                    f"- `out/ICLR_2026_Conference_authors.csv` — {len(iclr_authors)} rows, "
                    f"{len(iclr_authors[0])} cols\n"
                    f"- `out/ICML_2025_Conference_papers.csv` — {len(icml_papers)} rows, "
                    f"{len(icml_papers[0])} cols")

    sections.append("---\n# ICLR 2026 — Output I (papers)")

    # one oral, one poster, one reject
    by_type = {}
    for r in iclr_papers:
        by_type.setdefault(r["type"], r)

    for t in ["Accept (Oral)", "Accept (Poster)", "Reject"]:
        if t in by_type:
            sections.append(render_paper(by_type[t], f"ICLR 2026 — example: {t}"))

    sections.append("---\n# ICLR 2026 — Output II (authors)")
    pcl = next((r for r in iclr_authors if "Pierre-Carl" in r["Name"]), iclr_authors[0])
    sections.append(render_author(pcl, f"Author profile: {pcl['Name']}"))

    sections.append("---\n# ICML 2025 — Cross-venue adaptivity check")
    sections.append(
        "Same scraper, different conference. Note the different rating field "
        "(`overall_recommendation` instead of ICLR's `rating/soundness/...`) "
        "and the spotlight-poster bucket that ICLR doesn't have."
    )
    icml_sample = next((r for r in icml_papers if r["type"] == "Accept (oral)"),
                       icml_papers[0])
    sections.append(render_paper(icml_sample, f"ICML 2025 — example: {icml_sample['type']}"))

    PREVIEW.write_text("\n\n".join(sections), encoding="utf-8")
    print(f"Wrote {PREVIEW}")


if __name__ == "__main__":
    main()
